### ISSUE TITLE
Long-running mirroring causes rebalance issues

### ISSUE THREAD

**Issue by nscuro** [DependencyTrack/hyades#304]
When mirroring the NVD without an API key, the whole procedure takes way longer than when an API key is provided.

The Kafka Streams thread is effectively blocked while mirroring. During processing, it is not sending heartbeats to the Kafka broker, causing it to be kicked out of the consumer group (broker assumes it's dead):

```
2023-02-01 18:09:40,677 WARN  [org.apa.kaf.str.pro.int.StreamThread] (hyades-mirror-service-fe261319-eda1-44ee-a748-c5f33f51e2f8-StreamThread-1) stream-thread [hyades-mirror-service-fe261319-eda1-44ee-a748-c5f33f51e2f8-StreamThread-1] Detected that the thread is being fenced. This implies that this thread missed a rebalance and dropped out of the consumer group. Will close out all assigned tasks and rejoin the consumer group.: org.apache.kafka.streams.errors.TaskMigratedException: Consumer committing offsets failed, indicating the corresponding thread is no longer part of the group; it means all tasks belonging to this thread should be migrated.
        at org.apache.kafka.streams.processor.internals.TaskExecutor.commitOffsetsOrTransaction(TaskExecutor.java:225)
        at org.apache.kafka.streams.processor.internals.TaskExecutor.commitTasksAndMaybeUpdateCommittableOffsets(TaskExecutor.java:157)
        at org.apache.kafka.streams.processor.internals.TaskManager.commitTasksAndMaybeUpdateCommittableOffsets(TaskManager.java:1118)
        at org.apache.kafka.streams.processor.internals.TaskManager.commit(TaskManager.java:1086)
        at org.apache.kafka.streams.processor.internals.StreamThread.maybeCommit(StreamThread.java:1066)
        at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:801)
        at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:588)
        at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:550)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
Caused by: org.apache.kafka.clients.consumer.CommitFailedException: Offset commit cannot be completed since the consumer is not part of an active group for auto partition assignment; it is likely that the consumer was kicked out of the group.
        at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.sendOffsetCommitRequest(ConsumerCoordinator.java:1311)
        at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.commitOffsetsSync(ConsumerCoordinator.java:1168)
        at org.apache.kafka.clients.consumer.KafkaConsumer.commitSync(KafkaConsumer.java:1506)
        at org.apache.kafka.clients.consumer.KafkaConsumer.commitSync(KafkaConsumer.java:1453)
        at org.apache.kafka.streams.processor.internals.TaskExecutor.commitOffsetsOrTransaction(TaskExecutor.java:222)
        ... 9 more
```

**Comment by nscuro** [comment]
Revisiting this problem, I don't think we can use Kafka Streams for mirroring tasks. 

It's not really made for long-running tasks, and by long-running I actually mean anything over a few seconds per event.

Spawning worker threads in the respective `Processor`s doesn't work, because we need to forward events, and `context()` can only be used in the current processor thread. If I execute `update` in a separate thread, I'm getting this exception:

```
org.apache.kafka.streams.errors.StreamsException: Current node is unknown. This can happen if 'forward()' is called in an illegal scope. The root cause could be that a 'Processor' or 'Transformer' instance is shared. To avoid this error, make sure that your suppliers return new instances each time 'get()' of Supplier is called and do not return the same object reference multiple times.
```

**Comment by nscuro** [comment]
Maybe implementing the mirroring logic as [Kafka Connect source tasks](https://docs.confluent.io/platform/current/connect/devguide.html#core-concepts-and-apis) would be a more efficient way.

**Comment by nscuro** [comment]
There is a more or less working prototype here: https://github.com/DependencyTrack/hyades/tree/mirror-service-x

![Untitled-2023-03-17-1933](https://user-images.githubusercontent.com/5693141/227563946-c248e7b6-4ae8-497d-80b8-e2b2a71e3743.png)

Still to do:

- [ ] Tests (!!!)
- [ ] Parsing logic
- [ ] OSV mirroring
- [ ] API server changes
  - Input topic for mirroring commands have changed; Previously multiple, now only one
  - Parsing has to be changed to Protobuf

**Comment by sahibamittal** [comment]
Branch for apiserver -> https://github.com/DependencyTrack/hyades-apiserver/tree/mirror-service-x

**Comment by nscuro** [comment]
The work on this fill fix multiple p1 issues:
* https://github.com/DependencyTrack/hyades/issues/304
* https://github.com/DependencyTrack/hyades/issues/354
* https://github.com/DependencyTrack/hyades/issues/244
