### ISSUE TITLE
Grouping `ComponentMetrics` events by project UUID sometimes fails due to `NullPointerException`s

### ISSUE THREAD

**Issue by nscuro** [DependencyTrack/hyades#384]
Occasionally, the metrics service crashes due to exceptions like the following:

```
2023-03-12 13:36:21,229 ERROR [org.apa.kaf.str.pro.int.TaskExecutor] (hyades-metrics-service-95e2d5ce-1f6d-455c-ae0d-6fa63b4f1fdb-StreamThread-2) stream-thread [hyades-metrics-service-95e2d5ce-1f6d-455c-ae0d-6fa63b4f1fdb-StreamThread-2] Failed to process stream task 0_1 due to the following error:: org.apache.kafka.streams.errors.StreamsException: Exception caught in process. taskId=0_1, processor=consume_from_dtrack.metrics.component_topic, topic=dtrack.metrics.component, partition=1, offset=3, stacktrace=java.lang.NullPointerException
        at org.hyades.MetricsTopology.lambda$metricsTopology$0(MetricsTopology.java:71)
        at org.apache.kafka.streams.kstream.internals.KStreamImpl.lambda$internalSelectKey$0(KStreamImpl.java:243)
        at org.apache.kafka.streams.kstream.internals.KStreamMap$KStreamMapProcessor.process(KStreamMap.java:46)
        at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:157)
        at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forwardInternal(ProcessorContextImpl.java:290)
        at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:269)
        at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:228)
        ...
```

The reported line number `71` corresponds to this part of the code:

https://github.com/DependencyTrack/hyades/blob/03bc9de84e92b68b3c6d0af6745fc6320dbe3963/metrics-service/src/main/java/org/hyades/MetricsTopology.java#L70-L73

While I can't say for sure *which* field is `null` here, I suspect it's `getProject` that returns `null`. That would indicate that the API server, when serializing the `ComponentMetrics` object, did not load the `project` field.

Probably related to #369, as we're currently sending too much data anyway, and we do not have sufficient control over the content of the events.

**Comment by nscuro** [comment]
Searching in the Redpanda console reveals that it is indeed **one** occurrence where the `project` field(s) are populated with solely the `active` field.

![image](https://user-images.githubusercontent.com/5693141/224552441-5ff6fd17-500f-409f-b625-e39a64903780.png)

So instead of `project` being `null`, it's the `uuid`. No idea why this is happening, all ~10k events in my case are for the same project, and only one of them has this problem.

I used [`bloated.bom.json`](https://github.com/DependencyTrack/hyades/blob/main/load-tests/fixtures/boms/bloated.bom.json), and this is not happening every time.
